create table if not exists public.riot_legacy_snapshots (
  id bigint generated by default as identity primary key,
  puuid text not null,
  game_name text not null,
  tag_line text not null,
  platform text not null,
  snapshot_date date not null default current_date,
  captured_at timestamptz not null default now(),
  lol jsonb not null default '{}'::jsonb,
  tft jsonb not null default '{}'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  constraint riot_legacy_snapshots_identity_day_key unique (puuid, platform, snapshot_date)
);

create index if not exists riot_legacy_snapshots_puuid_captured_idx
  on public.riot_legacy_snapshots (puuid, captured_at desc);

alter table public.riot_legacy_snapshots enable row level security;

revoke all on table public.riot_legacy_snapshots from anon, authenticated;
grant all on table public.riot_legacy_snapshots to service_role;

comment on table public.riot_legacy_snapshots is
  'Daily server-managed Riot Legacy snapshots. Not directly exposed to browser roles.';
