create table if not exists public.riot_legacy_rso_states (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  state_hash text not null unique,
  redirect_uri text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists riot_legacy_rso_states_user_exp_idx
  on public.riot_legacy_rso_states (user_id, expires_at desc);

alter table public.riot_legacy_rso_states enable row level security;

revoke all on table public.riot_legacy_rso_states from anon, authenticated;
grant all on table public.riot_legacy_rso_states to service_role;

comment on table public.riot_legacy_rso_states is
  'Short-lived server-managed OAuth state for future Riot Sign On ownership verification.';
