create table if not exists public.riot_legacy_public_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  puuid text not null,
  platform text not null,
  public_slug text not null unique,
  is_public boolean not null default false,
  indexing_opt_in boolean not null default false,
  ownership_method text,
  ownership_verified_at timestamptz,
  published_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint riot_legacy_public_profiles_user_identity_key unique (user_id, puuid, platform),
  constraint riot_legacy_public_profiles_slug_check check (public_slug ~ '^[a-z0-9][a-z0-9-]{2,63}$'),
  constraint riot_legacy_public_profiles_public_requires_verification check (
    not is_public or ownership_verified_at is not null
  ),
  constraint riot_legacy_public_profiles_index_requires_public check (
    not indexing_opt_in or is_public
  )
);

create index if not exists riot_legacy_public_profiles_puuid_idx
  on public.riot_legacy_public_profiles (puuid, platform);

alter table public.riot_legacy_public_profiles enable row level security;

revoke all on table public.riot_legacy_public_profiles from anon, authenticated;
grant all on table public.riot_legacy_public_profiles to service_role;

comment on table public.riot_legacy_public_profiles is
  'Server-managed Riot Legacy public profile opt-ins. Publication requires verified account ownership.';
